# Generated by Django 3.0.5 on 2022-12-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0002_auto_20221130_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topings',
            new_name='Toping',
        ),
    ]
