# Generated by Django 3.0.5 on 2022-12-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0004_auto_20221205_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toping',
            new_name='Topping',
        ),
    ]
